---
title: "Replication of Study by Kim & Kim (2024, PNAS)"
author: "Jinwoo Lee (jil527@ucsd.edu)"
date: "`r format(Sys.time(), '%B %d, %Y')`".
format:
  html:
    toc: true
    toc_depth: 3
---

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

## Introduction
### Motivation
For my First Year Project, I aim to extend the **Anna Karenina** model testing framework (Finn et al., 2020 *NeuroImage*), which is increasingly used as a representative methodology in social and affective neuroscience, into a multivariate approach. This framework will help identify and validate the psychological profiles that best explain individual differences in brain function or structure. Building on this, during my PhD I plan to apply this framework to naturalistic neuroimaging data to address one of my core theoretical questions: *Which combination of psychological profiles best explain individual differences in how the brain encodes emotion concepts?*

As a first step, it will be valuable to practice traditional Anna Karenina modeling in affective neuroscience by reproducing key findings from prior studies and replicating them on new datasets. I chose Kim & Kim (2022 *PNAS*) as a target of replication project. Using Anna Karenina model, this paper tested the hypothesis that higher trait anxiety would be correlated with greater heterogeneity in morphology of amygdala-vmPFC pathway. They reported the weak but significant correlations (*r* = .13). 

### Overall Plan
My plan is to (1) **reproduce** these findings using the original German LEMON dataset employed in the study, and (2) **replicate** the results with a new open dataset at the high-level, WECANDOIT, which includes the same trait anxiety measures and white matter tractography data from about 150 Korean adolescents. Through this, I hope to examine how generalizable structural brain differences are in explaining specific emotional traits, while also training the methodological framework that will serve as the foundation of my First Year Project. 

### Stimuli, Procedures, and Expected Challenges
I do not expect major challenges in data acquisition, but I anticipate some conceptual/analytic challenges in understanding and implementing the analytic framework. Since the study is observational rather than experimentally manipulated, there were no stimuli presented; participants only completed demographic and psychological assessments before MRI scanning. For replication, I plan to use the aforementioned Korean open dataset, WECANDOIT, so I do not foresee practical obstacles in data collection procedures. 

However, there are two main challenges in understanding and practicing the Anna Karenina framework.
* First, Anna Karenina model testing does not test correlations at the level of individual samples, but rather at the level of their combinations. For example, Kim & Kim (2022 *PNAS*) tested the correlations of averaged trait anxiety scores and neuroanatomical dissimilarity between participants. Since these pairwise combinations are not statistically independent, standard correlation tests cannot be directly applied. I need to better understand how this issue is addressed in practice. 
* Second, in the study, morphological dissimilarity in amygdala-vmPFC white matter pathway between two participants was quantified using Euclidean distance (see Fig 2 in the paper). However, it is not clear for me which specific metrics were used to compute this distance - *What does this metric mean by the distance between what?*

By carefully working through the analysis script and resolving these two conceptual challenges, I aim to successfuly complete the replication project. 


## Methods

### Power Analysis

Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size.  Considerations of feasibility for selecting planned sample size.

### Planned Sample

Planned sample size and/or termination rule, sampling frame, known demographics if any, preselection rules if any.

### Materials

All materials - can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Procedure	

Can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Analysis Plan

Can also quote directly, though it is less often spelled out effectively for an analysis strategy section.  The key is to report an analysis strategy that is as close to the original - data cleaning rules, data exclusion rules, covariates, etc. - as possible.  

**Clarify key analysis of interest here**  You can also pre-specify additional analyses you plan to do.

### Differences from Original Study

Explicitly describe known differences in sample, setting, procedure, and analysis plan from original study.  The goal, of course, is to minimize those differences, but differences will inevitably occur.  Also, note whether such differences are anticipated to make a difference based on claims in the original article or subsequent published research on the conditions for obtaining the effect.

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


## Results


### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
### Data Preparation

#### Load Relevant Libraries and Functions

#### Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

### Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
